using System.Collections.Generic;
using UnityEngine;

namespace NewHorizons.Models;

/// <summary>
///     Record representing Human data used to migrate between cities.
/// </summary>
public record HumanMigrationRecord(
    ActorMigrationRecord ActorHumanData,
    string Seed,
    Human.ShoeType Footwear,
    float SpeedMultiplier,
    float MovementWalkSpeed,
    float MovementRunSpeed,
    float WalkingSpeedRatio,
    float BreathRecoveryRate,
    float SocietalClass,
    Descriptors Descriptors,
    CitizenOutfitController OutfitController,
    HandwritingPreset Handwriting,
    string Birthday,
    string CitizenName,
    string FirstName,
    string CasualName,
    string SurName,
    float GenderScale,
    Human.Gender Gender,
    Human.Gender BirthGender,
    float SlangUsage,
    float Sexuality,
    float Homosexuality,
    List<Human.Gender> AttractedTo,
    Human.BloodType BloodType,
    int FavColourIndex,
    float Humility,
    float Emotionality,
    float Extraversion,
    float Agreeableness,
    float Conscientiousness,
    float Creativity,
    float SleepNeedMultiplier,
    Vector2 LimitHumility,
    Vector2 LimitEmotionality,
    Vector2 LimitExtraversion,
    Vector2 LimitAgreeableness,
    Vector2 LimitConscientiousness,
    Vector2 LimitCreativity,
    List<Human.Trait> CharacterTraits,
    float BrokenLeg,
    float Bruised,
    float BlackEye,
    float Numb,
    float StarchAddiction,
    float SyncDiskInstall,
    float Blinded,
    int SightingMemoryLimit,
    List<Human.Wound> CurrentWounds,
    List<Human.WalletItem> WalletItems,
    int PreferredBookCount,
    GameplayController.Passcode Passcode,
    CharacterTrait PasswordTrait)
{
    /// <summary>
    ///    Constructor for HumanMigrationRecord.
    /// </summary>
    /// <param name="human"> The Human to migrate. </param>
    public HumanMigrationRecord(Human human) : this(
        new ActorMigrationRecord(human),
        human.seed,
        human.footwear,
        human.speedMultiplier,
        human.movementWalkSpeed,
        human.movementRunSpeed,
        human.walkingSpeedRatio,
        human.breathRecoveryRate,
        human.societalClass,
        human.descriptors,
        human.outfitController,
        human.handwriting,
        human.birthday,
        human.citizenName,
        human.firstName,
        human.casualName,
        human.surName,
        human.genderScale,
        human.gender,
        human.birthGender,
        human.slangUsage,
        human.sexuality,
        human.homosexuality,
        human.attractedTo,
        human.bloodType,
        human.favColourIndex,
        human.humility,
        human.emotionality,
        human.extraversion,
        human.agreeableness,
        human.conscientiousness,
        human.creativity,
        human.sleepNeedMultiplier,
        human.limitHumility,
        human.limitEmotionality,
        human.limitExtraversion,
        human.limitAgreeableness,
        human.limitConscientiousness,
        human.limitCreativity,
        human.characterTraits,
        human.brokenLeg,
        human.bruised,
        human.blackEye,
        human.numb,
        human.starchAddiction,
        human.syncDiskInstall,
        human.blinded,
        human.sightingMemoryLimit,
        human.currentWounds,
        human.walletItems,
        human.preferredBookCount,
        human.passcode,
        human.passwordTrait)
    {
    }
}